const express = require('express');
const cors = require('cors');
const fetch = require('node-fetch');

const app = express();
app.use(cors());
app.use(express.json());

const PORT = process.env.PORT || 43180;
const USER_AGENT = 'Restore/1.0 (Penistone Insight Hub)';

// Ward feeds first (already scoped). Borough feed is keyword-filtered.
// Do not append ?type=MTW — FixMyStreet returns 503 for that query.
const SOURCES = [
  { name: 'Penistone East ward', url: 'https://www.fixmystreet.com/rss/reports/Barnsley/Penistone+East', wardMatch: true, area: 'Penistone East' },
  { name: 'Penistone West ward', url: 'https://www.fixmystreet.com/rss/reports/Barnsley/Penistone+West', wardMatch: true, area: 'Penistone West' },
  { name: 'Barnsley borough (keyword filtered)', url: 'https://www.fixmystreet.com/rss/reports/Barnsley', wardMatch: false, area: 'Penistone' }
];

const VILLAGE_KEYWORDS = [
  'penistone', 'thurlstone', 'millhouse green', 'hoylandswaine', 'cubley',
  'oxspring', 'springvale', 'spring vale', 'ingbirchworth', 'hunshelf',
  'langsett', 'midhopestones', 'bullhouse', 'gunthwaite', 'silkstone',
  'thurgoland'
];

let cachedReports = [];
let lastFetch = 0;
const sourceCache = {};
const sourceHealth = {};

function decodeEntities(str) {
  return (str || '')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&#10;/g, '\n')
    .replace(/&amp;/g, '&');
}

function extractTag(itemXml, tag) {
  const re = new RegExp(`<${tag}[^>]*>([\\s\\S]*?)<\\/${tag}>`, 'i');
  const m = itemXml.match(re);
  return m ? m[1].trim() : '';
}

function cleanTitle(title) {
  const t = title.replace(/,\s*\d{1,2}(st|nd|rd|th)\s+[A-Za-z]+$/, '').trim();
  return t || 'Untitled report';
}

function extractLoc(desc) {
  const m = desc.match(/Nearest road to the pin placed on the map \(automatically generated by OpenStreetMap\):\s*([^<\n]+)/i);
  return m ? m[1].trim() : 'Penistone area';
}

function extractPhoto(desc) {
  const m = desc.match(/<img[^>]+src="([^"]+)"/i);
  return m ? m[1] : null;
}

function cleanDescription(desc) {
  return desc
    .replace(/<img[^>]*>/gi, '')
    .replace(/Nearest road to the pin[\s\S]*$/i, '')
    .replace(/<br\s*\/?>/gi, ' ')
    .replace(/<a[^>]*>[\s\S]*?<\/a>/gi, '')
    .replace(/&#\d+;/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function mapCategory(category, title) {
  const c = (category || '').toLowerCase();
  const t = (title || '').toLowerCase();
  if (c.includes('pothole') || c.includes('road') || c.includes('highway') || c.includes('pavement') || c.includes('footpath') || t.includes('pothole')) return 'pothole';
  if (c.includes('rubbish') || c.includes('flytip') || c.includes('flyposting') || c.includes('street cleaning') || c.includes('dog fouling') || t.includes('litter') || t.includes('rubbish') || t.includes('dump')) return 'litter';
  if (c.includes('street lighting') || t.includes('light') || t.includes('lamp')) return 'lighting';
  if (t.includes('noise') || t.includes('anti-social') || t.includes('anti social') || t.includes('asb')) return 'asb';
  return 'other';
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function fetchRssSourceOnce(source) {
  const res = await fetch(source.url, {
    headers: {
      'User-Agent': USER_AGENT,
      Accept: 'application/rss+xml, application/xml;q=0.9, text/xml;q=0.8, */*;q=0.7',
      'Accept-Language': 'en-GB,en;q=0.9'
    },
    timeout: 15000
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const xml = await res.text();
  const itemBlocks = xml.match(/<item[\s\S]*?<\/item>/g) || [];
  const items = [];

  itemBlocks.forEach((block) => {
    const rawTitle = decodeEntities(extractTag(block, 'title'));
    const link = extractTag(block, 'link').trim();
    const rawDesc = decodeEntities(extractTag(block, 'description'));
    const category = extractTag(block, 'category');
    const pubDate = extractTag(block, 'pubDate');
    const pointText = extractTag(block, 'georss:point');

    let lat = null;
    let lng = null;
    if (pointText) {
      const parts = pointText.split(/\s+/).map(Number);
      if (parts.length === 2 && !Number.isNaN(parts[0]) && !Number.isNaN(parts[1])) {
        [lat, lng] = parts;
      }
    }

    const title = cleanTitle(rawTitle);
    const combined = `${title} ${rawDesc}`.toLowerCase();

    if (!source.wardMatch && !VILLAGE_KEYWORDS.some((v) => combined.includes(v))) return;
    if (!link) return;

    items.push({
      id: link,
      title,
      loc: extractLoc(rawDesc),
      area: source.area || 'Penistone',
      lat,
      lng,
      type: mapCategory(category, title),
      severity: /pothole|flood|dangerous|blocked|collapsed|unsafe|sunk/i.test(title) ? 'high' : 'normal',
      ts: pubDate ? new Date(pubDate).getTime() : Date.now(),
      time: 'Recent',
      url: link,
      media: extractPhoto(rawDesc),
      desc: cleanDescription(rawDesc),
      source: source.name
    });
  });

  return items;
}

async function fetchRssSource(source, attempts = 3) {
  let lastErr;
  for (let i = 0; i < attempts; i += 1) {
    try {
      const items = await fetchRssSourceOnce(source);
      sourceHealth[source.name] = { ok: true, count: items.length, lastError: null };
      return items;
    } catch (err) {
      lastErr = err;
      console.warn(` ${source.name} attempt ${i + 1}/${attempts} failed: ${err.message}`);
      if (i < attempts - 1) await sleep(1500 * (i + 1));
    }
  }
  sourceHealth[source.name] = {
    ok: false,
    count: (sourceCache[source.name] || []).length,
    lastError: lastErr ? lastErr.message : 'unknown'
  };
  throw lastErr;
}

async function fetchReports() {
  console.log('Fetching reports from all sources...');
  const results = await Promise.allSettled(SOURCES.map((source) => fetchRssSource(source)));

  const merged = new Map();
  results.forEach((r, i) => {
    const name = SOURCES[i].name;
    if (r.status === 'fulfilled') {
      sourceCache[name] = r.value;
      console.log(` ${name}: ${r.value.length} reports`);
    } else {
      console.error(` ${name} failed after retries: ${r.reason && r.reason.message} — using last known data (${(sourceCache[name] || []).length} reports)`);
    }
    (sourceCache[name] || []).forEach((item) => merged.set(item.id, item));
  });

  cachedReports = Array.from(merged.values()).sort((a, b) => b.ts - a.ts);
  lastFetch = Date.now();
  console.log(`Loaded ${cachedReports.length} total reports`);
}

fetchReports();
setInterval(fetchReports, 12 * 60 * 1000);

app.get('/api/reports', (req, res) => {
  res.json({
    updated: lastFetch ? new Date(lastFetch).toISOString() : null,
    count: cachedReports.length,
    reports: cachedReports
  });
});

app.get('/health', (req, res) => {
  const sources = {};
  SOURCES.forEach((source) => {
    const health = sourceHealth[source.name] || { ok: false, count: 0, lastError: 'not fetched yet' };
    sources[source.name] = {
      ok: health.ok,
      count: (sourceCache[source.name] || []).length,
      lastError: health.lastError
    };
  });
  res.json({
    ok: true,
    service: 'Restore / Penistone Insight Hub',
    updated: lastFetch ? new Date(lastFetch).toISOString() : null,
    lastFetch,
    count: cachedReports.length,
    sources
  });
});

app.get('/', (req, res) => {
  res.send('Restore / Penistone Insight Hub backend is running');
});

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
